name: angular_dart_demo
version: 0.0.1
dependencies:
  angular:
    git: git://github.com/angular/angular.dart.git #version: 0.9.11
  shadow_dom: any
dev_dependencies:
  unittest: any
transformers:
- angular
