name: angular_dart_demo
version: 0.0.1
dependencies:
  angular: #0.10.0
    git:
      ref: rename
      url: git://github.com/angular/angular.dart.git
  browser: any
  js: any
  shadow_dom: any
  http_server: any
  route_hierarchical: '>=0.4.18 <0.5.0'
dev_dependencies:
  unittest: any
transformers:
- angular
