name: angular_dart_demo
version: 0.0.1
dependencies:
  angular:
    git: git://github.com/angular/angular.dart.git #version: 0.9.11
  browser: any
  js: any
  shadow_dom: any
  http_server: any
dev_dependencies:
  unittest: any
transformers:
- angular:
    html_files:
    - lib/rating/rating_component.html
    template_uri_rewrites:
      packages/: /packages/